### ISSUE TITLE
Vipul long-term tasks

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#58]
## Personal projects: long-pending work

This is work that involves projects or task types that I haven't dealt with for a while, so it is likely that there is some initial inertia against them; also they may need more concentrated time.

### MediaWiki/Subwiki

- [ ] Upgrade subwikis to latest version of MediaWiki, and document update process
- [ ] Migrate the remaining subwikis over to the new version of MediaWiki (there were 4-5 of them that still haven't been migrated)

### Diet Watch

- [x] Set up Diet Watch repository, SQL table schema, and initial data

### Subwiki error reports

- [x] Catch up on error reports backlog, and set cadence for regular review of error reports
  - I am considering this mostly done; there are some errors that I still need to investigate in more depth and then fix, but at least I've gone through the whole list.

### PW

- [ ] Consider moving PW to MediaWiki

### CDP

- [x] Move the hosting of CDP to my server
- [x] Think through next steps of expansion for CDP
  - Keep a close watch on answers to @riceissa's LessWrong question https://www.lesswrong.com/posts/9YwNXt7ANyMqTu6Ky/degree-of-duplication-and-coordination-in-projects-that

### DDDP

- [x] Schedule some time for thorough review of DDDP, with @riceissa available to answer questions and allow for a rapid feedback loop of development and testing

## Personal projects: ongoing tasks

See https://github.com/vipulnaik/daily-updates/blob/master/ongoing-maintenance.md

**Comment by Mati-Roy** [comment]
Does PW = Priority.Wiki?

**Comment by riceissa** [comment]
> Does PW = Priority.Wiki?

No, it stands for People Watch/People Watching. The project isn't public at the moment but you can find more information at https://contractwork.vipulnaik.com/venue.php?venue=People+repo
